name: "GitHub Actions Documentation Generator"
description: "Generates comprehensive documentation for GitHub Actions workflows"
author: "your-username"
branding:
  icon: "book-open"
  color: "blue"

inputs:
  workflow_files:
    description: "Glob pattern for workflow files to document"
    required: false
    default: ".github/workflows/*.yml"
  output_dir:
    description: "Directory to write documentation to"
    required: false
    default: "docs/workflows"
  format:
    description: "Output format (markdown, html)"
    required: false
    default: "markdown"
  generate_diagrams:
    description: "Whether to generate diagrams"
    required: false
    default: "true"
  diagram_format:
    description: "Format for generated diagrams (png, svg, pdf)"
    required: false
    default: "png"
  include_source:
    description: "Include source code in documentation"
    required: false
    default: "false"
  ai_enhancement:
    description: "Enable AI-powered enhancements"
    required: false
    default: "false"
  ai_api_key:
    description: "API key for AI service"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Node.js for Mermaid CLI
      uses: actions/setup-node@v3
      if: ${{ inputs.generate_diagrams == 'true' }}
      with:
        node-version: "16"

    - name: Install Mermaid CLI
      if: ${{ inputs.generate_diagrams == 'true' }}
      run: npm install -g @mermaid-js/mermaid-cli
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Generate documentation
      run: python ${{ github.action_path }}/src/main_improved.py
      shell: bash
      env:
        INPUT_WORKFLOW_FILES: ${{ inputs.workflow_files }}
        INPUT_OUTPUT_DIR: ${{ inputs.output_dir }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_GENERATE_DIAGRAMS: ${{ inputs.generate_diagrams }}
        INPUT_DIAGRAM_FORMAT: ${{ inputs.diagram_format }}
        INPUT_INCLUDE_SOURCE: ${{ inputs.include_source }}
        INPUT_AI_ENHANCEMENT: ${{ inputs.ai_enhancement }}
        INPUT_AI_API_KEY: ${{ inputs.ai_api_key }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
