name: End-to-End Documentation Example

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "!.github/workflows/generate-docs.yml"
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to commit documentation to"
        required: false
        default: "main"
      pr_branch:
        description: "Create PR to this branch instead of direct commit"
        required: false
        default: ""

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate documentation
        uses: your-username/gha-doc@v1
        with:
          workflow_files: ".github/workflows/*.yml"
          output_dir: "docs/workflows"
          format: "markdown"
          generate_diagrams: true
          include_source: false

      # Create Mermaid rendered images
      - name: Install Mermaid CLI
        run: |
          npm install -g @mermaid-js/mermaid-cli

      - name: Convert Mermaid to Images
        run: |
          mkdir -p .mermaid_temp
          for file in docs/workflows/*.mmd; do
            echo "Converting $file to PNG..."
            mmdc -i "$file" -o "${file%.mmd}.png" -b transparent
          done

      # Option 1: Direct commit to the same branch
      - name: Commit documentation changes (direct)
        id: commit_direct
        if: ${{ github.event.inputs.pr_branch == '' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update workflow documentation"
          file_pattern: "docs/workflows/*"
          branch: ${{ github.event.inputs.target_branch || github.ref_name }}

      # Option 2: Create PR
      - name: Commit documentation changes (PR)
        id: commit_pr
        if: ${{ github.event.inputs.pr_branch != '' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update workflow documentation"
          title: "Update workflow documentation"
          body: |
            This PR updates the GitHub Actions workflow documentation.

            Generated automatically by the GitHub Actions Documentation Generator.
          branch: docs/workflow-documentation-update
          base: ${{ github.event.inputs.pr_branch }}
          path: docs/workflows/

      - name: Get PR URL
        if: ${{ github.event.inputs.pr_branch != '' && steps.commit_pr.outputs.pull-request-number != '' }}
        run: |
          echo "Documentation update PR created: ${{ steps.commit_pr.outputs.pull-request-url }}"
