name: Update Workflow Documentation

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "!.github/workflows/update-docs.yml" # Don't trigger itself
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
  workflow_dispatch: # Manual trigger
    inputs:
      create_pr:
        description: "Create PR with documentation updates"
        type: boolean
        default: true
      deploy_to_github_pages:
        description: "Deploy to GitHub Pages"
        type: boolean
        default: false
  schedule:
    - cron: "0 0 * * 1" # Weekly on Monday at midnight

jobs:
  document:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for accurate changes

      - name: Generate documentation
        uses: gitopsiq/gha-doc@v1
        with:
          workflow_files: ".github/workflows/*.yml"
          output_dir: "docs/workflows"
          format: "html"
          generate_diagrams: true
          include_diagram_type: "svg"
          include_source: false

          # AI enhancement configuration
          ai_enhancement: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
          ai_provider: "openai" # Options: openai, azure_openai, anthropic, hf, mock

          # OpenAI configuration (if using openai provider)
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_model: "gpt-4"

          # Azure OpenAI configuration (if using azure_openai provider)
          # azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          # azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          # azure_openai_deployment: "gpt-4"

          # Anthropic configuration (if using anthropic provider)
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # anthropic_model: "claude-2"

          # Hugging Face configuration (if using hf provider)
          # hf_api_key: ${{ secrets.HF_API_KEY }}
          # hf_model: "mistralai/Mistral-7B-Instruct-v0.1"

          # GitHub Pages deployment
          deploy_to_github_pages: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy_to_github_pages }}

      - name: Check for documentation changes
        id: check_changes
        run: |
          if git diff --quiet docs/workflows/; then
            echo "No changes detected in documentation."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in documentation."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # If triggered by PR, comment with preview link
      - name: Comment on PR with documentation preview
        if: |
          github.event_name == 'pull_request' &&
          steps.check_changes.outputs.has_changes == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const files = fs.readdirSync('./docs/workflows/').filter(f => f.endsWith('.html'));

            let comment = '## 📄 Workflow Documentation Changes\n\n';
            comment += 'This PR would update the following workflow documentation:\n\n';

            files.forEach(file => {
              comment += `- ${file}\n`;
            });

            comment += '\nPlease review the changes before merging this PR.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      # Option 1: Create a PR with changes (default)
      - name: Create Pull Request for docs
        if: |
          (github.event_name == 'push' ||
           github.event_name == 'schedule' ||
           (github.event_name == 'workflow_dispatch' && inputs.create_pr == true)) &&
          steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: update workflow documentation"
          title: "📄 Auto-Update Workflow Documentation"
          body: |
            This PR was automatically generated by the Workflow Documentation Generator.

            It updates the documentation for workflow files that have changed.

            Please review the changes before merging.
          branch: docs/workflow-updates
          base: main
          labels: documentation, automated-pr
          delete-branch: true

      # Option 2: Direct commit (if specified)
      - name: Commit documentation changes
        if: |
          github.event_name == 'workflow_dispatch' &&
          inputs.create_pr == false &&
          steps.check_changes.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit-message: "docs: update workflow documentation"
          file_pattern: "docs/workflows/*"
